required = [
  "github.com/fatih/color",
  "github.com/go-sql-driver/mysql",
  "github.com/jinzhu/copier",
  "github.com/joho/godotenv",
  "github.com/pkg/errors",
  "github.com/rollbar/rollbar-go",
  "go.uber.org/zap",
  "github.com/jinzhu/gorm",
  "github.com/jinzhu/inflection",
  "github.com/swaggo/gin-swagger",
  "github.com/alecthomas/template",
  "github.com/swaggo/swag"
]

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/rollbar/rollbar-go"
  version = "1.0.2"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "github.com/swaggo/gin-swagger"
  version = "1.0.0"
